// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoFixTools():Promise<main.AutoFixReport>;

export function BrowsePath(arg1:string):Promise<string>;

export function CheckPathExists(arg1:string):Promise<boolean>;

export function ClearLogs():Promise<number>;

export function ConfirmMinimize():Promise<void>;

export function ConfirmQuit():Promise<void>;

export function CreateConfigBackup():Promise<void>;

export function DiagnoseTools():Promise<main.DiagnosticReport>;

export function DiagnoseToolsByIDs(arg1:Array<string>):Promise<main.DiagnosticReport>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function ExecuteCommandAsAdmin(arg1:string,arg2:string):Promise<string>;

export function ExecuteCommandInTerminal(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteJavaTool(arg1:main.RuntimeToolRequest):Promise<main.RuntimeToolResult>;

export function ExecutePythonTool(arg1:main.RuntimeToolRequest):Promise<main.RuntimeToolResult>;

export function ExecuteWithEnvironment(arg1:Record<string, any>):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetConfigBackups():Promise<Array<main.BackupInfo>>;

export function GetCurrentWindowSize():Promise<Record<string, number>>;

export function GetEnvironment():Promise<Record<string, any>>;

export function GetEnvironmentStatus():Promise<Record<string, any>>;

export function GetExeIcon(arg1:string):Promise<string>;

export function GetLogs(arg1:string,arg2:number):Promise<Array<main.LogEntry>>;

export function GetPortablePathInfo():Promise<Record<string, any>>;

export function LogFrontend(arg1:string,arg2:string):Promise<void>;

export function LogRunEvent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MinimizeWindow():Promise<boolean>;

export function OpenLogFile():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RestoreConfigBackup(arg1:string):Promise<main.Config>;

export function RunStartupDiagnostics():Promise<main.StartupDiagnosticResult>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveCurrentWindowSize():Promise<Record<string, number>>;

export function SaveEnvironment(arg1:Record<string, any>):Promise<void>;

export function ShowCloseConfirm():Promise<void>;

export function StartApplication(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartApplicationAsAdmin(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartApplicationTool(arg1:main.ApplicationToolRequest):Promise<main.ApplicationToolResult>;

export function ToggleMaximizeWindow():Promise<boolean>;

export function UpdateShowWindowHotkey(arg1:string):Promise<string>;
