// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowsePath(arg1:string):Promise<string>;

export function CheckPathExists(arg1:string):Promise<boolean>;

export function ConfirmMinimize():Promise<void>;

export function ConfirmQuit():Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function ExecuteCommandAsAdmin(arg1:string,arg2:string):Promise<string>;

export function ExecuteCommandInTerminal(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteWithEnvironment(arg1:Record<string, any>):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetEnvironment():Promise<Record<string, any>>;

export function GetEnvironmentStatus():Promise<Record<string, any>>;

export function GetExeIcon(arg1:string):Promise<string>;

export function GetLogs(arg1:string,arg2:number):Promise<Array<main.LogEntry>>;

export function LogFrontend(arg1:string,arg2:string):Promise<void>;

export function LogRunEvent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MinimizeWindow():Promise<boolean>;

export function OpenLogFile():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveEnvironment(arg1:Record<string, any>):Promise<void>;

export function ShowCloseConfirm():Promise<void>;

export function StartApplication(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartApplicationAsAdmin(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleMaximizeWindow():Promise<boolean>;

export function UpdateShowWindowHotkey(arg1:string):Promise<string>;
