// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoFixTools() {
  return window['go']['main']['App']['AutoFixTools']();
}

export function BrowsePath(arg1) {
  return window['go']['main']['App']['BrowsePath'](arg1);
}

export function CheckPathExists(arg1) {
  return window['go']['main']['App']['CheckPathExists'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ConfirmMinimize() {
  return window['go']['main']['App']['ConfirmMinimize']();
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function CreateConfigBackup() {
  return window['go']['main']['App']['CreateConfigBackup']();
}

export function DiagnoseTools() {
  return window['go']['main']['App']['DiagnoseTools']();
}

export function DiagnoseToolsByIDs(arg1) {
  return window['go']['main']['App']['DiagnoseToolsByIDs'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExecuteCommandAsAdmin(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommandAsAdmin'](arg1, arg2);
}

export function ExecuteCommandInTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteCommandInTerminal'](arg1, arg2, arg3);
}

export function ExecuteJavaTool(arg1) {
  return window['go']['main']['App']['ExecuteJavaTool'](arg1);
}

export function ExecutePythonTool(arg1) {
  return window['go']['main']['App']['ExecutePythonTool'](arg1);
}

export function ExecuteWithEnvironment(arg1) {
  return window['go']['main']['App']['ExecuteWithEnvironment'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigBackups() {
  return window['go']['main']['App']['GetConfigBackups']();
}

export function GetCurrentWindowSize() {
  return window['go']['main']['App']['GetCurrentWindowSize']();
}

export function GetEnvironment() {
  return window['go']['main']['App']['GetEnvironment']();
}

export function GetEnvironmentStatus() {
  return window['go']['main']['App']['GetEnvironmentStatus']();
}

export function GetExeIcon(arg1) {
  return window['go']['main']['App']['GetExeIcon'](arg1);
}

export function GetLogs(arg1, arg2) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2);
}

export function GetPortablePathInfo() {
  return window['go']['main']['App']['GetPortablePathInfo']();
}

export function LogFrontend(arg1, arg2) {
  return window['go']['main']['App']['LogFrontend'](arg1, arg2);
}

export function LogRunEvent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogRunEvent'](arg1, arg2, arg3, arg4);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RestoreConfigBackup(arg1) {
  return window['go']['main']['App']['RestoreConfigBackup'](arg1);
}

export function RunStartupDiagnostics() {
  return window['go']['main']['App']['RunStartupDiagnostics']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCurrentWindowSize() {
  return window['go']['main']['App']['SaveCurrentWindowSize']();
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function ShowCloseConfirm() {
  return window['go']['main']['App']['ShowCloseConfirm']();
}

export function StartApplication(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartApplication'](arg1, arg2, arg3);
}

export function StartApplicationAsAdmin(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartApplicationAsAdmin'](arg1, arg2, arg3);
}

export function StartApplicationTool(arg1) {
  return window['go']['main']['App']['StartApplicationTool'](arg1);
}

export function ToggleMaximizeWindow() {
  return window['go']['main']['App']['ToggleMaximizeWindow']();
}

export function UpdateShowWindowHotkey(arg1) {
  return window['go']['main']['App']['UpdateShowWindowHotkey'](arg1);
}
